language: node
sudo: true
dist: trusty
node_js:
  - "node"

branches:
  only:
    - travisci    #Master only builds for prod. For now changing it to Travis CI Branch
                  #dev branch push will triger build for non prod deployment

install:
- npm install electron-builder@next

cache:
  directories:
  - "$HOME/.npm"
before_script:
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
  # - sudo apt-get install npm
  - npm config set strict-ssl false
  - mkdir dist2
  #Cloning other repos
  - git clone https://github.com/Kitsune-tools/Ana-Analytics-Dashboard.git
  - git clone https://github.com/Kitsune-tools/ANAChat-Web.git
  - rm -rf node_modules/
  #For analytics-dash
  - cd Ana-Analytics-Dashboard/
  - npm i npm@latest -g
  - npm install typings -g
  - npm i @angular-devkit/core
  - npm install -g @angular/cli@1.6.1
  - npm i node-sass
  - npm ci
  - ng build --prod --aot=false
  - cd ..
  - mkdir dist2/analytics-dashboard
  - cp -R Ana-Analytics-Dashboard/dist/* dist2/analytics-dashboard/
  - ls -l
  - ls -l Ana-Analytics-Dashboard/
  #For Chat-Web
  - cd ANAChat-Web/
  - npm i node-sass
  - npm install
  - ng build --prod --aot=false
  - cd ..
  - mkdir dist2/simulator  # For web chat
  - ls -l ANAChat-Web/
  - cp -R ANAChat-Web/dist/* dist2/simulator/
  # For ana APP
  - npm cache clean --force
  - ls -l
  - npm ci
  - ng build --prod --aot=false
  - ls -l
  - mkdir dist/simulator
  - mkdir dist/analytics-dashboard
  - cp -R dist2/simulator/* dist/simulator/
  - cp -R dist2/analytics-dashboard/* dist/analytics-dashboard/
  
script:
  - npm install -g electron-builder
  - npm install -g popper.js
  - npm install -g jquery
  - apt install snap
  - apt install snapd
  - snap install snapcraft --classic
  - cd dist/
  - npm install
  - electron-builder

notifications:
  email:
    - soumyajit.dutta@nowfloats.com
    # - khaja.nizamuddin@nowfloats.com
  slack:
    on_success: always
    on_failure: always