language: node_js
node_js:
  - "node"

sudo: true
dist: trusty

branches:
  only:
    - travisci    #Master only builds for prod. For now changing it to Travis CI Branch
                  #dev branch push will triger build for non prod deployment

before_script:
  - mkdir dist2
  #Cloning other repos
  - git clone https://github.com/Kitsune-tools/Ana-Analytics-Dashboard.git
  - git clone https://github.com/Kitsune-tools/ANAChat-Web.git
  #For analytics-dash
  - npm install @angular-devkit/core
  - npm install -g @angular/cli@1.6.1
  - npm install typings -g
  - npm i -g npm@5.7.1 Ana-Analytics-Dashboard/
  - npm i node-sass Ana-Analytics-Dashboard/
  - npm ci Ana-Analytics-Dashboard/
  - npm install -g @angular/cli@1.6.1 Ana-Analytics-Dashboard/
  - ng build --prod --aot=false Ana-Analytics-Dashboard/ Ana-Analytics-Dashboard/
  - mkdir dist2/analytics-dashboard
  - cp -R dist/* dist2/analytics-dashboard/
  - ls -l
  - ls -l Ana-Analytics-Dashboard/
  #For Chat-Web
  - npm install ANAChat-Web/
  - ng build --prod --aot=false ANAChat-Web/ ANAChat-Web/
  - mkdir dist2/simulator  # For web chat
  - ls -l ANAChat-Web/
  - cp -R dist/* dist2/simulator/
  # For ana APP
  - npm install
  - ng build --prod --aot=false
  - ls -l
  - mkdir dist/simulator
  - mkdir dist/analytics-dashboard
  - cp -R dist2/simulator/* dist/simulator/
  - cp -R dist2/analytics-dashboard/* dist/analytics-dashboard/
  
script:
  - npm install -g electron-builder
  - npm install -g popper.js
  - npm install -g jquery
  - apt install snap
  - snap install snapcraft --classic
  - cd dist/
  - npm install
  - electron-builder

notifications:
  email:
    - soumyajit.dutta@nowfloats.com
    - khaja.nizamuddin@nowfloats.com
  slack:
    on_success: always
    on_failure: always