language: node_js
node_js:
  - "node"

sudo: true
dist: trusty

branches:
  only:
    - travisci    #Master only builds for prod. For now changing it to Travis CI Branch
                  #dev branch push will triger build for non prod deployment

before_script:
  # For ana APP
  - npm install @angular-devkit/core
  - npm install -g @angular/cli@1.6.1
  - npm install
  - ng build --prod --aot=false
  #Cloning other repos
  - git clone https://github.com/Kitsune-tools/Ana-Analytics-Dashboard.git
  - git clone https://github.com/Kitsune-tools/ANAChat-Web.git
  #For Chat-Web
  - npm install ANAChat-Web/
  - ng build --prod --aot=false ANAChat-Web/ ANAChat-Web/
  #For analytics-dash
  - npm install typings -g
  - npm i -g npm@5.7.1 Ana-Analytics-Dashboard/
  - npm i node-sass Ana-Analytics-Dashboard/
  - npm ci Ana-Analytics-Dashboard/
  - npm install -g @angular/cli@1.6.1 Ana-Analytics-Dashboard/
  - ng build --prod --aot=false Ana-Analytics-Dashboard/ Ana-Analytics-Dashboard/

  #Copying
  - mkdir dist/simulator  # For web chat
  - mkdir dist/analytics-dashboard # For analytics dash
  - cp -R ANAChat-Web/dist/* dist/simulator
  - cp -R Ana-Analytics-Dashboard/dist/* dist/analytics-dashboard

script:
  - rm -R release/
  - ./dist/electron-builder

notifications:
  email:
    - soumyajit.dutta@nowfloats.com
    - khaja.nizamuddin@nowfloats.com
  slack:
    on_success: always
    on_failure: always