language: node_js
node_js:
  - "v9.5.0"

sudo: true
dist: trusty

branches:
  only:
    - travisci    #Master only builds for prod. For now changing it to Travis CI Branch
                  #dev branch push will triger build for non prod deployment
install:
  - npm i -g npm@5.6.0 # this should be deleted once 5.7.X is out of "pre-release"
  # - npm install          # instead of default npm install 

before_script:
  - mkdir dist2
  - npm install 
  - ng build --prod --aot=false
  #Cloning other repos
  - git clone https://github.com/Kitsune-tools/Ana-Analytics-Dashboard.git
  - git clone https://github.com/Kitsune-tools/ANAChat-Web.git
  - rm -rf node_modules/
  #For analytics-dash
  - cd Ana-Analytics-Dashboard/
  - npm install typings -g
  - npm i @angular-devkit/core
  - npm install -g @angular/cli@1.6.1
  - npm i node-sass
  - npm install
  - ng build --prod --aot=false
  - cd ..
  - mkdir dist2/analytics-dashboard
  - cp -R Ana-Analytics-Dashboard/dist/* dist2/analytics-dashboard/
  - ls -l
  - ls -l Ana-Analytics-Dashboard/
  #For Chat-Web
  - cd ANAChat-Web/
  - npm i node-sass
  - npm install
  - ng build --prod --aot=false
  - cd ..
  - mkdir dist2/simulator  # For web chat
  - ls -l ANAChat-Web/
  - cp -R ANAChat-Web/dist/* dist2/simulator/
  # For ana APP
  - npm cache verify
  - npm install -g npm@5.6.0
  - ls -l
  - ls -l
  - mkdir dist/simulator
  - mkdir dist/analytics-dashboard
  - cp -R dist2/simulator/* dist/simulator/
  - cp -R dist2/analytics-dashboard/* dist/analytics-dashboard/
  
script:
  - npm install -g electron-builder
  - npm install -g popper.js
  - npm install -g jquery
  - apt install snap
  - apt install snapd
  - snap install snapcraft --classic
  - cd dist/
  - electron-builder

notifications:
  email:
    # - soumyajit.dutta@nowfloats.com
    # - khaja.nizamuddin@nowfloats.com