environment:
  nodejs_version: "9.5.0"

platform:
  - x86
  - x64

# Post-install test scripts.
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% EQU 0.8 npm config set strict-ssl false
  - IF %nodejs_version% LSS 4 npm -g install npm@2
  - IF %nodejs_version% EQU 5 npm -g install npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - IF %nodejs_version% LSS 1 (npm test) ELSE (IF %nodejs_version% LSS 4 (iojs node_modules\tap\bin\tap.js --gc test/js/*-test.js) ELSE (node node_modules\tap\bin\tap.js --gc test/js/*-test.js))

build: off